model_name: tinystories_small_5
run_number: 1
dataset_path: /mnt/ssd/huggingface/datasets/TinyStories_preprocessed/
tokenizer_path: ./SL/tokenizers/TinyStories_tokenizer_2.json
hardware_batch_size: 64
effective_batch_size: 512
d_model: 512
num_heads: 8
num_layers: 8
dropout: 0.0
seq_len: 256
ff_d: 2048
max_steps: 30000
label_smoothing: 0.0
weight_decay: 0.0
initial_lr: 0.003
min_lr: 0.0001
warmup_steps: 100
decay_steps: 30000
current_step: 3000
current_lr: 0.0029332987394393166
current_sample_idx: 1535488
steps/metrics: 10
steps/save: 1000
start_time: 2025-09-08 15:24:00.048698
current_loss: 1.4098708629608154
current_time: 2025-09-08 15:57:15.771742
seed: 1337
bias: False
